//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebservicesApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class E1_E2
    {
        public int Id { get; set; }
        public int E1ID { get; set; }
        public int E2ID { get; set; }
    
        public virtual E1 E1 { get; set; }
        public virtual E2 E2 { get; set; }
    }
}
