//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebservicesApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenttable
    {
        public Studenttable()
        {
            this.SubjectDetails = new HashSet<SubjectDetail>();
            this.Subjecttables = new HashSet<Subjecttable>();
        }
    
        public int StudentId { get; set; }
        public string StudentName { get; set; }
    
        public virtual ICollection<SubjectDetail> SubjectDetails { get; set; }
        public virtual ICollection<Subjecttable> Subjecttables { get; set; }
    }
}
