//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebservicesApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectDetail
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SubjectId { get; set; }
    
        public virtual Studenttable Studenttable { get; set; }
        public virtual Subjecttable Subjecttable { get; set; }
    }
}
